const Employees = [
    {
        id: '1',
        name: 'Chang',
        surname: 'Wang',
        image: require('../Images/Chang-Wang.jpg'),
        position: 'Copywriter',
        department: 'Creative Department',
        email: 'chang.wang@pixelpulsemedia.co.za',
        phone: '011-964-2035',
    },
    {
        id: '2',
        name: 'Ciara',
        surname: 'Jones',
        image: require('../Images/Ciara-Jones.jpg'),
        position: 'Accounts Manager',
        department: 'Client Services',
        email: 'ciara.jones@pixelpulsemedia.co.za',
        phone: '011-964-2019',
    },
    {
        id: '3',
        name: 'Drake',
        surname: 'Street',
        image: require('../Images/Drake-Street.jpg'),
        position: 'Search Engine Operation Specialist',
        department: 'Digital Marketing',
        email: 'drake.street@pixelpulsemedia.co.za',
        phone: '011-964-2005',
    },
    {
        id: '4',
        name: 'Ibrahim',
        surname: 'Naidoo',
        image: require('../Images/Ibrahim-Naidoo.jpg'),
        position: 'Market Research Analyst',
        department: 'Analytics and Insight',
        email: 'ibrahim.naidoo@pixelpulsemedia.co.za',
        phone: '011-964-2235',
    },
    {
        id: '5',
        name: 'Jessica',
        surname: 'van Tonder',
        image: require('../Images/Jessica-van-Tonder.jpg'),
        position: 'Web Developer',
        department: 'Technology and Development',
        email: 'jessica.vantonder@pixelpulsemedia.co.za',
        phone: '011-964-2050',
    },
    {
        id: '6',
        name: 'Lou',
        surname: 'Tang',
        image: require('../Images/Lou-Tang.jpg'),
        position: 'Media Director',
        department: 'Media Planning and Buying',
        email: 'lou.tang@pixelpulsemedia.co.za',
        phone: '011-964-2300',
    },
    {
        id: '7',
        name: 'Maria',
        surname: 'Rodreguaze',
        image: require('../Images/Maria-Rodreguaze.jpg'),
        position: 'Event Coordinator',
        department: 'Public Relations',
        email: 'maria.rodreguaze@pixelpulsemedia.co.za',
        phone: '011-964-2075',
    },
    {
        id: '8',
        name: 'Mark',
        surname: 'Seth',
        image: require('../Images/Mark-Seth.jpg'),
        position: 'Finanace Manager',
        department: 'Finance',
        email: 'mark.seth@pixelpulsemedia.co.za',
        phone: '011-964-2965',
    },
    {
        id: '9',
        name: 'Palesa',
        surname: 'Mokoena',
        image: require('../Images/Palesa-Mokoena.jpg'),
        position: 'Public Relations Manager',
        department: 'Public Relations',
        email: 'palesa.mokoena@pixelpulsemedia.co.za',
        phone: '011-964-2569',
    },
    {
        id: '10',
        name: 'Pernisha',
        surname: 'Khan',
        image: require('../Images/Pernisha-Khan.jpg'),
        position: 'Client Relations Manager',
        department: 'Client Service',
        email: 'pernisha.khan@pixelpulsemedia.co.za',
        phone: '011-964-2495',
    },
    {
        id: '11',
        name: 'Shane',
        surname: 'Eagels',
        image: require('../Images/Shane-Eagles.jpg'),
        position: 'Soue Chef',
        department: 'Facilities and Operations',
        email: 'shane.eagles@pixelpulsemedia.co.za',
        phone: '011-964-21954',
    },
    {
        id: '12',
        name: 'Thabo',
        surname: 'Radebe',
        image: require('../Images/Thabo-Radebe.jpg'),
        position: 'Operations Security Manager',
        department: 'Facilities and Operaions',
        email: 'thabo.radebe@pixelpulsemedia.co.za',
        phone: '011-964-27658',
    },
];

export default Employees;